### ISSUE TITLE
Introduce a flag for pubkeys

### ISSUE THREAD

**Issue by Phistr90** [ethereum/eth2-ssv#41]
Currently there is no flag to provide the pubkeys, it only can get the pubkeys from OS env. variables. A flag for the pubkeys like all other variables would be helpful.

Alternatively, it would be nice to have a flag that imports a config file.

**Comment by alonmuroch** [comment]
That will be dynamic via a smart contract in phase 2

**Comment by Phistr90** [comment]
> That will be dynamic via a smart contract in phase 2

Isnt that an overkill for some use cases? 

Like single entity that runs the ssv setup. I dont see the need for a smart contract there.
